### ISSUE TITLE
PHP 7.4 error

### ISSUE THREAD

**Issue by mynameisfreedom** [bnomei/kirby3-janitor#71]
Hi, the plugin version 2.15.0 doesn't work on PHP 7.4 because of the

`kirby3-janitor\vendor\composer\platform_check.php` and line 7

```
if (!(PHP_VERSION_ID >= 80002)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 8.0.2". You are running ' . PHP_VERSION . '.';
}
```
Is this a mistake from your side to disallow lower versions or there is something in the code that is not compatible with PHP 7.4?

**Comment by bnomei** [comment]
thanks for reporting. i updated a dependency which snug in another `symfony/deprecation-contracts` that was resolved to a php8. i will fix this and create a new release.

**Comment by janherman** [comment]
Hi! Maybe this or a similar bug came back in the latest version? My site crashes after I put janitor into my plugin folder. 

Janitor version: 2.16.2
Kirby version: 3.7.5
PHP: 7.4.25

2.16.0 seems to work fine.
